name: Lynx
main: marvtechnology.lynx.Lynx
version: 0.1.0
api-version: '1.20'
commands:
  country:
    description: Country commands
  faction:
    description: Faction commands
  lynx:
    description: General lynx command
  admin:
    description: Admin commands
  countrybank:
    description: Bank commands
